# Generated by Django 4.0.5 on 2022-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_alter_product_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='application_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='contract_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
