# Generated by Django 4.0.5 on 2022-07-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_alter_prelead_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='monthly_loan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
