# Generated by Django 4.0.5 on 2022-07-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_prelead_monthly_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='applied_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='currency',
            field=models.CharField(choices=[('ALL', 'ALL'), ('EURO', 'EURO')], default='ALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='partner_channel',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='seller_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
