# Generated by Django 4.0.5 on 2022-07-13 21:46

from django.db import migrations, models
import partners.validators


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_alter_prelead_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='currency',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('EURO', 'EURO')], default='ALL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='doc_1',
            field=models.FileField(blank=True, null=True, upload_to='file/additional_docs/%Y/%m/%d/', validators=[partners.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='doc_2',
            field=models.FileField(blank=True, null=True, upload_to='file/additional_docs/%Y/%m/%d/', validators=[partners.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='loan_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='partner_contract',
            field=models.FileField(blank=True, null=True, upload_to='file/partner_contracts/%Y/%m/%d/', validators=[partners.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='uw_contract',
            field=models.FileField(blank=True, null=True, upload_to='file/uw_contracts/%Y/%m/%d/', validators=[partners.validators.validate_file_extension]),
        ),
    ]
