# Generated by Django 4.0.5 on 2022-07-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_alter_prelead_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='partner_channel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
