# Generated by Django 4.0.5 on 2022-07-07 22:27

from django.db import migrations, models
import django.db.models.deletion
import partners.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personal_id', models.CharField(max_length=10)),
                ('nr_tel', models.CharField(max_length=16)),
                ('nipt', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.member')),
            ],
            options={
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_assigned', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.product')),
            ],
            options={
                'db_table': 'partner_products',
            },
        ),
        migrations.CreateModel(
            name='LoanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_loan_term', models.IntegerField(blank=True, null=True)),
                ('max_loan_term', models.IntegerField(blank=True, null=True)),
                ('interest', models.FloatField()),
                ('fee', models.FloatField(blank=True, null=True)),
                ('total_sum', models.FloatField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.product')),
            ],
            options={
                'db_table': 'loan_configs',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('personal_id', models.CharField(max_length=11)),
                ('id_card_doc', models.FileField(upload_to='file/id_cards/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('klauzole_doc', models.FileField(upload_to='file/clausoles/%Y/%m/%d/', validators=[partners.validators.validate_file_extension])),
                ('birthdate', models.DateField()),
                ('mobile', models.CharField(max_length=16)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('status', models.CharField(max_length=50)),
                ('consent_boa', models.CharField(max_length=10)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
    ]
