# Generated by Django 4.0.5 on 2022-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_loanconfig_bonus_alter_loanconfig_interest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanconfig',
            old_name='fee',
            new_name='application_commission',
        ),
        migrations.RenameField(
            model_name='loanconfig',
            old_name='interest',
            new_name='customer_interest',
        ),
        migrations.AddField(
            model_name='loanconfig',
            name='partner_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
