# Generated by Django 4.0.5 on 2022-07-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_rename_fee_loanconfig_application_commission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanconfig',
            old_name='partner_fee',
            new_name='partner_fee_without_bonus',
        ),
        migrations.AddField(
            model_name='loanconfig',
            name='partner_fee_with_bonus',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
